### ISSUE TITLE
Unit test build but some are failing

### ISSUE THREAD

**Issue by cneubauerUSGS** [USGS-Astrogeology/isis3_cmake#13]
Unit Test are being worked on, there was issues with exclude files causing the output to be blank by not pipping output correctly to compare. App test are working on both systems.

**Comment by Kelvinrr** [comment]
Probably worth restructuring app tests? Current strategy of recycling the existing makefiles doesn't mix well with the goal of eliminating the makefiles. In which case, what is a simple of way of doing that without clobbering existing tests. 

Another question: how should testing workflow look like with CMake?

**Comment by cneubauerUSGS** [comment]
It is counter to what we want as an end goal. However is there anyway to do it without getting rid of current tests that wouldn't involve some form of recreation of the makefiles in cmake? Its just a command sequence so realistically I'm sure with a clever enough script we could take those commands and copy them into our cmake files but then at that point we are having to write a cmake file or function for each future test. At that point is there a real benefit to moving from the current Makefiles for tests?

**Comment by cneubauerUSGS** [comment]
This is now fixed Unit Test and App Test mirror the old make system
