### ISSUE TITLE
add findOpenGL

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/isis3_cmake#25]
Moses was having an issue where his build wasn't finding OpenGL headers forcing him to manually inject the flags. Writing a findOpenGL module seems like the best approach to figuring this out.

**Comment by jlaura** [comment]
https://cmake.org/cmake/help/v3.0/module/FindOpenGL.html

?

**Comment by Kelvinrr** [comment]
Should be good to go with #27 and #26
