### ISSUE TITLE
CMake prob on OSX

### ISSUE THREAD

**Issue by michaelaye** [USGS-Astrogeology/isis3_cmake#33]
I'm not sure you support OSX, but it should be very close to the Unix path.
Anyhow, my current try to follow the instructions here:
https://github.com/USGS-Astrogeology/isis3_cmake/wiki/Build-Instructions
break at the cmake command:

`cmake -DCMAKE_INSTALL_PREFIX=<install directory> ..`
with the error:
```bash
CMake Error: The source directory "/Users/klay6683/src/isis3_cmake/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

macOS 10.12.6 on a Macbook Air, cmake via homebrew.

**Comment by michaelaye** [comment]
I just noticed that you provide a conda env to work with this, so i installed it, but it did not change above error message.

**Comment by jlaura** [comment]
@michaelaye Please see the [cmake branch of the ISIS3 repo](https://github.com/USGS-Astrogeology/ISIS3/tree/cmake).

I will update this repo to indicate that it is deprecated and all dev. work is being done inside of ISIS3 proper.

**Comment by michaelaye** [comment]
Thanks. Trent gave me this link, that’s how I tried it. Also, the difference in time for the most recent commit was 2 days (9 vs 11 days old), so it wasn’t really obvious.

**Comment by jlaura** [comment]
:+1: Please let me know how this goes.  I am going to repopen this issues (I did not realize that the ISIS3 team has issues turned off on their repo...)

**Comment by michaelaye** [comment]
The error messages stays the same. I did a "find . -name CMakeLists.txt" on the cmake branch for ISIS3 but that file does not exist, so no dice.

**Comment by jlaura** [comment]
@Kelvinrr @cneubauerUSGS Can you assist?

**Comment by michaelaye** [comment]
Oh, I was wrong. Found the Wiki with the more detailed instructions. the Cmake is now running, sorry.

**Comment by jlaura** [comment]
:+1:

**Comment by michaelaye** [comment]
Do you want compile probs here, or with a new issue that does NOT relate to CMake?

**Comment by michaelaye** [comment]
i think it's better to make a new issue that doesn't confuse by title.
