### ISSUE TITLE
Reverted code: REV:8209

### ISSUE THREAD

**Issue by chrisryancombs** [USGS-Astrogeology/isis3_cmake#4]
A large commit was reverted back in svn Revision #8209:

(http://subversion.wr.usgs.gov/websvn/comp.php?repname=ISIS+Development+Repository&compare[]=/isis3/branches/cmake/isis/cmake/@8208&compare[]=/isis3/branches/cmake/isis/cmake/@8209)

to "to get back to a working system."

Im going to see about integrating some of these changes again, as they simplified some of the issues we were looking into

**Comment by Kelvinrr** [comment]
It seems this was taken care of by #5 and #8
